### PR TITLE
Add DRIVE_DIRECT capability

### PR DESCRIPTION
**Pull request by EdoB**
As described in the official [doc](http://www.irobot.com/filelibrary/create/Create%20Open%20Interface_v2.pdf#page=9) the DRIVE_DIRECT command allows to send independently the speed(mm/sec) to the wheels.
This functionality is useful for example when combined with the input of a joystick.

### CODE REVIEW

**Comment by drzaiusx11** [comment]
Thanks for the pull request, looks great

**Comment by EdoB** [comment]
Thanks, I will PR again if I add something else! ;)

**Comment by EdoB** [comment]
I see on [npmjs.com](https://www.npmjs.com/package/create-oi) that the version is still the 0.0.4.
Do you have to update manually that or is going to fetch automatically the change?

**Comment by drzaiusx11** [comment]
I'm away from my node development machine for a couple days, so I've created an issue [here](https://github.com/drzaiusx11/create-oi/issues/3) to manually publish the latest  when I get back

**Pull request merged**
